#!/bin/bash

data=$(curl -k -d "username=$username&password=$password" -X POST URL_FOR_AUTHENTICATION);
# echo "Username: $username Password: $password  Curl Response: $data" >> vpn.log;
if [[ $data -ne 0 ]];then
        echo -e "Not Authenticated" >>vpn.log;
        exit 1;
fi
exit 0;
